language: php

php:
  - 5.5
  - 5.6
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - composer test:db
  - composer test:security
  - composer test:phpunit
  - bin/behat --suite=api_features --strict --colors
  - bin/behat --suite=front_features --strict --colors
  - php bin/php-cs-fixer fix --no-interaction --dry-run --diff src
  - php bin/php-cs-fixer fix --no-interaction --dry-run --diff features
