language: php

php:
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - GITHUB_PAGES_COMMIT_MESSAGE="Rebuild pages at $(git rev-parse --short HEAD)"
    - if [[ -z "$GITHUB_PAGES_TOKEN" ]]; then
        GITHUB_PAGES_REMOTE="https://user:${GITHUB_PAGES_TOKEN}@github.com/in6pio/Incipio.git";
      fi;
    - GITHUB_USER_NAME="TravisBot"
    - GITHUB_USER_EMAIL="travisbot@incipio.fr"

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.6
      env: DEPLOY_BUILD=true
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - pip install --upgrade pip --user
  - composer self-update
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit --no-update
  - for file in scripts/*.sh; do
      echo -en "\e[34mimports ${file}\e[0m\n";
      source "$file";
    done;
  - setupCoverage
  - setupDeployment

install:
  - composer global update --prefer-dist
  - composer install --prefer-dist
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - composer test:db
  - composer test:security
  - composer test:phpunit
  - composer test:behat:api
  - composer test:behat:front

after_success:
  - publishToGithubPages

after_script:
  - sendCoverageData
