parameters:
    Mgate.etude_manager.class: Mgate\SuiviBundle\Manager\EtudeManager
    Mgate.doctype_manager.class: Mgate\SuiviBundle\Manager\DocTypeManager
    Mgate.chart_manager.class: Mgate\SuiviBundle\Manager\ChartManager

services:
    Mgate.etude_manager:
        class: "%Mgate.etude_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@app.json_key_value_store"
        tags:
            - { name: twig.extension }
    Mgate.doctype_manager:
        class: "%Mgate.doctype_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
    Mgate.chart_manager:
        class: "%Mgate.chart_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@Mgate.etude_manager"
          - "@logger"
          - "@app.json_key_value_store"

    form.type_extension.help_message:
        class: Mgate\SuiviBundle\Form\Extension\HelpMessageTypeExtension
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\AbstractTypeExtension}

    Mgate.email_etu:
            class: Mgate\SuiviBundle\Manager\EmailEtuManager
            arguments:
              - "@app.json_key_value_store"
